[package]
name = "projinfo"
version = "0.1.0"
edition = "2021"
authors = ["dk949"]

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
