use crate::arg_parser::FileType;
use lazy_static::lazy_static;
use std::collections::HashMap;

#[derive(Debug)]
pub struct Lang {
    name: &'static str,
    category: FileType,
}

lazy_static! {
    #[rustfmt::skip]
    pub static ref LANGS: HashMap<&'static str, &'static[Lang]> = HashMap::from([
        (".abap", &[Lang{name: "ABAP", category: FileType::Programming}][..]),
        (".asc", &[Lang{name: "AGS Script", category: FileType::Programming},Lang{name: "AsciiDoc", category: FileType::Prose},Lang{name: "Public Key", category: FileType::Data}][..]),
        (".ash", &[Lang{name: "AGS Script", category: FileType::Programming}][..]),
        (".ampl", &[Lang{name: "AMPL", category: FileType::Programming}][..]),
        (".mod", &[Lang{name: "AMPL", category: FileType::Programming},Lang{name: "Linux Kernel Module", category: FileType::Data},Lang{name: "Modula-2", category: FileType::Programming},Lang{name: "XML", category: FileType::Data}][..]),
        (".g4", &[Lang{name: "ANTLR", category: FileType::Programming}][..]),
        (".apib", &[Lang{name: "API Blueprint", category: FileType::Markup}][..]),
        (".apl", &[Lang{name: "APL", category: FileType::Programming}][..]),
        (".dyalog", &[Lang{name: "APL", category: FileType::Programming}][..]),
        (".asp", &[Lang{name: "ASP", category: FileType::Programming}][..]),
        (".asax", &[Lang{name: "ASP", category: FileType::Programming}][..]),
        (".ascx", &[Lang{name: "ASP", category: FileType::Programming}][..]),
        (".ashx", &[Lang{name: "ASP", category: FileType::Programming}][..]),
        (".asmx", &[Lang{name: "ASP", category: FileType::Programming}][..]),
        (".aspx", &[Lang{name: "ASP", category: FileType::Programming}][..]),
        (".axd", &[Lang{name: "ASP", category: FileType::Programming}][..]),
        (".dats", &[Lang{name: "ATS", category: FileType::Programming}][..]),
        (".hats", &[Lang{name: "ATS", category: FileType::Programming}][..]),
        (".sats", &[Lang{name: "ATS", category: FileType::Programming}][..]),
        (".as", &[Lang{name: "ActionScript", category: FileType::Programming}][..]),
        (".adb", &[Lang{name: "Ada", category: FileType::Programming}][..]),
        (".ada", &[Lang{name: "Ada", category: FileType::Programming}][..]),
        (".ads", &[Lang{name: "Ada", category: FileType::Programming}][..]),
        (".agda", &[Lang{name: "Agda", category: FileType::Programming}][..]),
        (".als", &[Lang{name: "Alloy", category: FileType::Programming}][..]),
        (".apacheconf", &[Lang{name: "ApacheConf", category: FileType::Markup}][..]),
        (".vhost", &[Lang{name: "ApacheConf", category: FileType::Markup},Lang{name: "Nginx", category: FileType::Markup}][..]),
        (".cls", &[Lang{name: "Apex", category: FileType::Programming},Lang{name: "OpenEdge ABL", category: FileType::Programming},Lang{name: "TeX", category: FileType::Markup},Lang{name: "Visual Basic", category: FileType::Programming}][..]),
        (".applescript", &[Lang{name: "AppleScript", category: FileType::Programming}][..]),
        (".scpt", &[Lang{name: "AppleScript", category: FileType::Programming}][..]),
        (".arc", &[Lang{name: "Arc", category: FileType::Programming}][..]),
        (".ino", &[Lang{name: "Arduino", category: FileType::Programming}][..]),
        (".asciidoc", &[Lang{name: "AsciiDoc", category: FileType::Prose}][..]),
        (".adoc", &[Lang{name: "AsciiDoc", category: FileType::Prose}][..]),
        (".aj", &[Lang{name: "AspectJ", category: FileType::Programming}][..]),
        (".asm", &[Lang{name: "Assembly", category: FileType::Programming}][..]),
        (".a51", &[Lang{name: "Assembly", category: FileType::Programming}][..]),
        (".inc", &[Lang{name: "Assembly", category: FileType::Programming},Lang{name: "C++", category: FileType::Programming},Lang{name: "HTML", category: FileType::Markup},Lang{name: "PAWN", category: FileType::Programming},Lang{name: "PHP", category: FileType::Programming},Lang{name: "POV-Ray SDL", category: FileType::Programming},Lang{name: "Pascal", category: FileType::Programming},Lang{name: "SQL", category: FileType::Data},Lang{name: "SourcePawn", category: FileType::Programming}][..]),
        (".nasm", &[Lang{name: "Assembly", category: FileType::Programming}][..]),
        (".aug", &[Lang{name: "Augeas", category: FileType::Programming}][..]),
        (".ahk", &[Lang{name: "AutoHotkey", category: FileType::Programming}][..]),
        (".ahkl", &[Lang{name: "AutoHotkey", category: FileType::Programming}][..]),
        (".au3", &[Lang{name: "AutoIt", category: FileType::Programming}][..]),
        (".awk", &[Lang{name: "Awk", category: FileType::Programming}][..]),
        (".auk", &[Lang{name: "Awk", category: FileType::Programming}][..]),
        (".gawk", &[Lang{name: "Awk", category: FileType::Programming}][..]),
        (".mawk", &[Lang{name: "Awk", category: FileType::Programming}][..]),
        (".nawk", &[Lang{name: "Awk", category: FileType::Programming}][..]),
        (".bat", &[Lang{name: "Batchfile", category: FileType::Programming}][..]),
        (".cmd", &[Lang{name: "Batchfile", category: FileType::Programming}][..]),
        (".befunge", &[Lang{name: "Befunge", category: FileType::Programming}][..]),
        (".bison", &[Lang{name: "Bison", category: FileType::Programming}][..]),
        (".bb", &[Lang{name: "BitBake", category: FileType::Programming},Lang{name: "BlitzBasic", category: FileType::Programming}][..]),
        (".decls", &[Lang{name: "BlitzBasic", category: FileType::Programming}][..]),
        (".bmx", &[Lang{name: "BlitzMax", category: FileType::Programming}][..]),
        (".bsv", &[Lang{name: "Bluespec", category: FileType::Programming}][..]),
        (".boo", &[Lang{name: "Boo", category: FileType::Programming}][..]),
        (".b", &[Lang{name: "Brainfuck", category: FileType::Programming},Lang{name: "Limbo", category: FileType::Programming}][..]),
        (".bf", &[Lang{name: "Brainfuck", category: FileType::Programming},Lang{name: "HyPhy", category: FileType::Programming}][..]),
        (".brs", &[Lang{name: "Brightscript", category: FileType::Programming}][..]),
        (".bro", &[Lang{name: "Bro", category: FileType::Programming}][..]),
        (".c", &[Lang{name: "C", category: FileType::Programming}][..]),
        (".cats", &[Lang{name: "C", category: FileType::Programming}][..]),
        (".h", &[Lang{name: "C", category: FileType::Programming},Lang{name: "C++", category: FileType::Programming},Lang{name: "Objective-C", category: FileType::Programming}][..]),
        (".idc", &[Lang{name: "C", category: FileType::Programming}][..]),
        (".w", &[Lang{name: "C", category: FileType::Programming}][..]),
        (".cs", &[Lang{name: "C#", category: FileType::Programming},Lang{name: "Smalltalk", category: FileType::Programming}][..]),
        (".cake", &[Lang{name: "C#", category: FileType::Programming},Lang{name: "CoffeeScript", category: FileType::Programming}][..]),
        (".cshtml", &[Lang{name: "C#", category: FileType::Programming}][..]),
        (".csx", &[Lang{name: "C#", category: FileType::Programming}][..]),
        (".cpp", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".c++", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".cc", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".cp", &[Lang{name: "C++", category: FileType::Programming},Lang{name: "Component Pascal", category: FileType::Programming}][..]),
        (".cxx", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".h++", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".hh", &[Lang{name: "C++", category: FileType::Programming},Lang{name: "Hack", category: FileType::Programming}][..]),
        (".hpp", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".hxx", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".inl", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".ipp", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".tcc", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".tpp", &[Lang{name: "C++", category: FileType::Programming}][..]),
        (".c-objdump", &[Lang{name: "C-ObjDump", category: FileType::Data}][..]),
        (".chs", &[Lang{name: "C2hs Haskell", category: FileType::Programming}][..]),
        (".clp", &[Lang{name: "CLIPS", category: FileType::Programming}][..]),
        (".cmake", &[Lang{name: "CMake", category: FileType::Programming}][..]),
        (".cmake.in", &[Lang{name: "CMake", category: FileType::Programming}][..]),
        (".cob", &[Lang{name: "COBOL", category: FileType::Programming}][..]),
        (".cbl", &[Lang{name: "COBOL", category: FileType::Programming}][..]),
        (".ccp", &[Lang{name: "COBOL", category: FileType::Programming}][..]),
        (".cobol", &[Lang{name: "COBOL", category: FileType::Programming}][..]),
        (".cpy", &[Lang{name: "COBOL", category: FileType::Programming}][..]),
        (".css", &[Lang{name: "CSS", category: FileType::Markup}][..]),
        (".csv", &[Lang{name: "CSV", category: FileType::Data}][..]),
        (".capnp", &[Lang{name: "Cap'n Proto", category: FileType::Programming}][..]),
        (".mss", &[Lang{name: "CartoCSS", category: FileType::Programming}][..]),
        (".ceylon", &[Lang{name: "Ceylon", category: FileType::Programming}][..]),
        (".chpl", &[Lang{name: "Chapel", category: FileType::Programming}][..]),
        (".ch", &[Lang{name: "Charity", category: FileType::Programming},Lang{name: "xBase", category: FileType::Programming}][..]),
        (".ck", &[Lang{name: "ChucK", category: FileType::Programming}][..]),
        (".cirru", &[Lang{name: "Cirru", category: FileType::Programming}][..]),
        (".clw", &[Lang{name: "Clarion", category: FileType::Programming}][..]),
        (".icl", &[Lang{name: "Clean", category: FileType::Programming}][..]),
        (".dcl", &[Lang{name: "Clean", category: FileType::Programming}][..]),
        (".click", &[Lang{name: "Click", category: FileType::Programming}][..]),
        (".clj", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".boot", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".cl2", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".cljc", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".cljs", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".cljs.hl", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".cljscm", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".cljx", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".hic", &[Lang{name: "Clojure", category: FileType::Programming}][..]),
        (".coffee", &[Lang{name: "CoffeeScript", category: FileType::Programming}][..]),
        ("._coffee", &[Lang{name: "CoffeeScript", category: FileType::Programming}][..]),
        (".cjsx", &[Lang{name: "CoffeeScript", category: FileType::Programming}][..]),
        (".cson", &[Lang{name: "CoffeeScript", category: FileType::Programming}][..]),
        (".iced", &[Lang{name: "CoffeeScript", category: FileType::Programming}][..]),
        (".cfm", &[Lang{name: "ColdFusion", category: FileType::Programming}][..]),
        (".cfml", &[Lang{name: "ColdFusion", category: FileType::Programming}][..]),
        (".cfc", &[Lang{name: "ColdFusion CFC", category: FileType::Programming}][..]),
        (".lisp", &[Lang{name: "Common Lisp", category: FileType::Programming},Lang{name: "NewLisp", category: FileType::Programming}][..]),
        (".asd", &[Lang{name: "Common Lisp", category: FileType::Programming}][..]),
        (".cl", &[Lang{name: "Common Lisp", category: FileType::Programming},Lang{name: "Cool", category: FileType::Programming},Lang{name: "OpenCL", category: FileType::Programming}][..]),
        (".l", &[Lang{name: "Common Lisp", category: FileType::Programming},Lang{name: "Groff", category: FileType::Markup},Lang{name: "Lex", category: FileType::Programming},Lang{name: "PicoLisp", category: FileType::Programming}][..]),
        (".lsp", &[Lang{name: "Common Lisp", category: FileType::Programming},Lang{name: "NewLisp", category: FileType::Programming}][..]),
        (".ny", &[Lang{name: "Common Lisp", category: FileType::Programming}][..]),
        (".podsl", &[Lang{name: "Common Lisp", category: FileType::Programming}][..]),
        (".sexp", &[Lang{name: "Common Lisp", category: FileType::Programming}][..]),
        (".cps", &[Lang{name: "Component Pascal", category: FileType::Programming}][..]),
        (".coq", &[Lang{name: "Coq", category: FileType::Programming}][..]),
        (".v", &[Lang{name: "Coq", category: FileType::Programming},Lang{name: "Verilog", category: FileType::Programming}][..]),
        (".cppobjdump", &[Lang{name: "Cpp-ObjDump", category: FileType::Data}][..]),
        (".c++-objdump", &[Lang{name: "Cpp-ObjDump", category: FileType::Data}][..]),
        (".c++objdump", &[Lang{name: "Cpp-ObjDump", category: FileType::Data}][..]),
        (".cpp-objdump", &[Lang{name: "Cpp-ObjDump", category: FileType::Data}][..]),
        (".cxx-objdump", &[Lang{name: "Cpp-ObjDump", category: FileType::Data}][..]),
        (".creole", &[Lang{name: "Creole", category: FileType::Prose}][..]),
        (".cr", &[Lang{name: "Crystal", category: FileType::Programming}][..]),
        (".feature", &[Lang{name: "Cucumber", category: FileType::Programming}][..]),
        (".cu", &[Lang{name: "Cuda", category: FileType::Programming}][..]),
        (".cuh", &[Lang{name: "Cuda", category: FileType::Programming}][..]),
        (".cy", &[Lang{name: "Cycript", category: FileType::Programming}][..]),
        (".pyx", &[Lang{name: "Cython", category: FileType::Programming}][..]),
        (".pxd", &[Lang{name: "Cython", category: FileType::Programming}][..]),
        (".pxi", &[Lang{name: "Cython", category: FileType::Programming}][..]),
        (".d", &[Lang{name: "D", category: FileType::Programming},Lang{name: "DTrace", category: FileType::Programming},Lang{name: "Makefile", category: FileType::Programming}][..]),
        (".di", &[Lang{name: "D", category: FileType::Programming}][..]),
        (".d-objdump", &[Lang{name: "D-ObjDump", category: FileType::Data}][..]),
        (".com", &[Lang{name: "DIGITAL Command Language", category: FileType::Programming}][..]),
        (".dm", &[Lang{name: "DM", category: FileType::Programming}][..]),
        (".zone", &[Lang{name: "DNS Zone", category: FileType::Data}][..]),
        (".arpa", &[Lang{name: "DNS Zone", category: FileType::Data}][..]),
        (".darcspatch", &[Lang{name: "Darcs Patch", category: FileType::Data}][..]),
        (".dpatch", &[Lang{name: "Darcs Patch", category: FileType::Data}][..]),
        (".dart", &[Lang{name: "Dart", category: FileType::Programming}][..]),
        (".diff", &[Lang{name: "Diff", category: FileType::Data}][..]),
        (".patch", &[Lang{name: "Diff", category: FileType::Data}][..]),
        (".dockerfile", &[Lang{name: "Dockerfile", category: FileType::Data}][..]),
        (".djs", &[Lang{name: "Dogescript", category: FileType::Programming}][..]),
        (".dylan", &[Lang{name: "Dylan", category: FileType::Programming}][..]),
        (".dyl", &[Lang{name: "Dylan", category: FileType::Programming}][..]),
        (".intr", &[Lang{name: "Dylan", category: FileType::Programming}][..]),
        (".lid", &[Lang{name: "Dylan", category: FileType::Programming}][..]),
        (".E", &[Lang{name: "E", category: FileType::Programming}][..]),
        (".ecl", &[Lang{name: "ECL", category: FileType::Programming},Lang{name: "ECLiPSe", category: FileType::Programming}][..]),
        (".eclxml", &[Lang{name: "ECL", category: FileType::Programming}][..]),
        (".sch", &[Lang{name: "Eagle", category: FileType::Markup},Lang{name: "KiCad", category: FileType::Programming}][..]),
        (".brd", &[Lang{name: "Eagle", category: FileType::Markup},Lang{name: "KiCad", category: FileType::Programming}][..]),
        (".epj", &[Lang{name: "Ecere Projects", category: FileType::Data}][..]),
        (".e", &[Lang{name: "Eiffel", category: FileType::Programming}][..]),
        (".ex", &[Lang{name: "Elixir", category: FileType::Programming}][..]),
        (".exs", &[Lang{name: "Elixir", category: FileType::Programming}][..]),
        (".elm", &[Lang{name: "Elm", category: FileType::Programming}][..]),
        (".el", &[Lang{name: "Emacs Lisp", category: FileType::Programming}][..]),
        (".emacs", &[Lang{name: "Emacs Lisp", category: FileType::Programming}][..]),
        (".emacs.desktop", &[Lang{name: "Emacs Lisp", category: FileType::Programming}][..]),
        (".em", &[Lang{name: "EmberScript", category: FileType::Programming}][..]),
        (".emberscript", &[Lang{name: "EmberScript", category: FileType::Programming}][..]),
        (".erl", &[Lang{name: "Erlang", category: FileType::Programming}][..]),
        (".es", &[Lang{name: "Erlang", category: FileType::Programming},Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".escript", &[Lang{name: "Erlang", category: FileType::Programming}][..]),
        (".hrl", &[Lang{name: "Erlang", category: FileType::Programming}][..]),
        (".xrl", &[Lang{name: "Erlang", category: FileType::Programming}][..]),
        (".yrl", &[Lang{name: "Erlang", category: FileType::Programming}][..]),
        (".fs", &[Lang{name: "F#", category: FileType::Programming},Lang{name: "Filterscript", category: FileType::Programming},Lang{name: "Forth", category: FileType::Programming},Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".fsi", &[Lang{name: "F#", category: FileType::Programming}][..]),
        (".fsx", &[Lang{name: "F#", category: FileType::Programming}][..]),
        (".fx", &[Lang{name: "FLUX", category: FileType::Programming},Lang{name: "HLSL", category: FileType::Programming}][..]),
        (".flux", &[Lang{name: "FLUX", category: FileType::Programming}][..]),
        (".f90", &[Lang{name: "FORTRAN", category: FileType::Programming}][..]),
        (".f", &[Lang{name: "FORTRAN", category: FileType::Programming},Lang{name: "Forth", category: FileType::Programming}][..]),
        (".f03", &[Lang{name: "FORTRAN", category: FileType::Programming}][..]),
        (".f08", &[Lang{name: "FORTRAN", category: FileType::Programming}][..]),
        (".f77", &[Lang{name: "FORTRAN", category: FileType::Programming}][..]),
        (".f95", &[Lang{name: "FORTRAN", category: FileType::Programming}][..]),
        (".for", &[Lang{name: "FORTRAN", category: FileType::Programming},Lang{name: "Formatted", category: FileType::Data},Lang{name: "Forth", category: FileType::Programming}][..]),
        (".fpp", &[Lang{name: "FORTRAN", category: FileType::Programming}][..]),
        (".factor", &[Lang{name: "Factor", category: FileType::Programming}][..]),
        (".fy", &[Lang{name: "Fancy", category: FileType::Programming}][..]),
        (".fancypack", &[Lang{name: "Fancy", category: FileType::Programming}][..]),
        (".fan", &[Lang{name: "Fantom", category: FileType::Programming}][..]),
        (".eam.fs", &[Lang{name: "Formatted", category: FileType::Data}][..]),
        (".fth", &[Lang{name: "Forth", category: FileType::Programming}][..]),
        (".4th", &[Lang{name: "Forth", category: FileType::Programming}][..]),
        (".forth", &[Lang{name: "Forth", category: FileType::Programming}][..]),
        (".fr", &[Lang{name: "Forth", category: FileType::Programming},Lang{name: "Frege", category: FileType::Programming},Lang{name: "Text", category: FileType::Prose}][..]),
        (".frt", &[Lang{name: "Forth", category: FileType::Programming}][..]),
        (".ftl", &[Lang{name: "FreeMarker", category: FileType::Programming}][..]),
        (".g", &[Lang{name: "G-code", category: FileType::Data},Lang{name: "GAP", category: FileType::Programming}][..]),
        (".gco", &[Lang{name: "G-code", category: FileType::Data}][..]),
        (".gcode", &[Lang{name: "G-code", category: FileType::Data}][..]),
        (".gms", &[Lang{name: "GAMS", category: FileType::Programming}][..]),
        (".gap", &[Lang{name: "GAP", category: FileType::Programming}][..]),
        (".gd", &[Lang{name: "GAP", category: FileType::Programming},Lang{name: "GDScript", category: FileType::Programming}][..]),
        (".gi", &[Lang{name: "GAP", category: FileType::Programming}][..]),
        (".tst", &[Lang{name: "GAP", category: FileType::Programming},Lang{name: "Scilab", category: FileType::Programming}][..]),
        (".s", &[Lang{name: "GAS", category: FileType::Programming}][..]),
        (".ms", &[Lang{name: "GAS", category: FileType::Programming},Lang{name: "Groff", category: FileType::Markup},Lang{name: "MAXScript", category: FileType::Programming}][..]),
        (".glsl", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".fp", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".frag", &[Lang{name: "GLSL", category: FileType::Programming},Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".frg", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".fsh", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".fshader", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".geo", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".geom", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".glslv", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".gshader", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".shader", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".vert", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".vrx", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".vsh", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".vshader", &[Lang{name: "GLSL", category: FileType::Programming}][..]),
        (".gml", &[Lang{name: "Game Maker Language", category: FileType::Programming},Lang{name: "Graph Modeling Language", category: FileType::Data},Lang{name: "XML", category: FileType::Data}][..]),
        (".kid", &[Lang{name: "Genshi", category: FileType::Programming}][..]),
        (".ebuild", &[Lang{name: "Gentoo Ebuild", category: FileType::Programming}][..]),
        (".eclass", &[Lang{name: "Gentoo Eclass", category: FileType::Programming}][..]),
        (".po", &[Lang{name: "Gettext Catalog", category: FileType::Prose}][..]),
        (".pot", &[Lang{name: "Gettext Catalog", category: FileType::Prose}][..]),
        (".glf", &[Lang{name: "Glyph", category: FileType::Programming}][..]),
        (".gp", &[Lang{name: "Gnuplot", category: FileType::Programming}][..]),
        (".gnu", &[Lang{name: "Gnuplot", category: FileType::Programming}][..]),
        (".gnuplot", &[Lang{name: "Gnuplot", category: FileType::Programming}][..]),
        (".plot", &[Lang{name: "Gnuplot", category: FileType::Programming}][..]),
        (".plt", &[Lang{name: "Gnuplot", category: FileType::Programming}][..]),
        (".go", &[Lang{name: "Go", category: FileType::Programming}][..]),
        (".golo", &[Lang{name: "Golo", category: FileType::Programming}][..]),
        (".gs", &[Lang{name: "Gosu", category: FileType::Programming},Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".gst", &[Lang{name: "Gosu", category: FileType::Programming}][..]),
        (".gsx", &[Lang{name: "Gosu", category: FileType::Programming}][..]),
        (".vark", &[Lang{name: "Gosu", category: FileType::Programming}][..]),
        (".grace", &[Lang{name: "Grace", category: FileType::Programming}][..]),
        (".gradle", &[Lang{name: "Gradle", category: FileType::Data}][..]),
        (".gf", &[Lang{name: "Grammatical Framework", category: FileType::Programming}][..]),
        (".graphql", &[Lang{name: "GraphQL", category: FileType::Data}][..]),
        (".dot", &[Lang{name: "Graphviz (DOT)", category: FileType::Data}][..]),
        (".gv", &[Lang{name: "Graphviz (DOT)", category: FileType::Data}][..]),
        (".man", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".1", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".1in", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".1m", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".1x", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".2", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".3", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".3in", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".3m", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".3qt", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".3x", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".4", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".5", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".6", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".7", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".8", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".9", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".me", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".n", &[Lang{name: "Groff", category: FileType::Markup},Lang{name: "Nemerle", category: FileType::Programming}][..]),
        (".rno", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".roff", &[Lang{name: "Groff", category: FileType::Markup}][..]),
        (".groovy", &[Lang{name: "Groovy", category: FileType::Programming}][..]),
        (".grt", &[Lang{name: "Groovy", category: FileType::Programming}][..]),
        (".gtpl", &[Lang{name: "Groovy", category: FileType::Programming}][..]),
        (".gvy", &[Lang{name: "Groovy", category: FileType::Programming}][..]),
        (".gsp", &[Lang{name: "Groovy Server Pages", category: FileType::Programming}][..]),
        (".hcl", &[Lang{name: "HCL", category: FileType::Programming}][..]),
        (".tf", &[Lang{name: "HCL", category: FileType::Programming}][..]),
        (".hlsl", &[Lang{name: "HLSL", category: FileType::Programming}][..]),
        (".fxh", &[Lang{name: "HLSL", category: FileType::Programming}][..]),
        (".hlsli", &[Lang{name: "HLSL", category: FileType::Programming}][..]),
        (".html", &[Lang{name: "HTML", category: FileType::Markup}][..]),
        (".htm", &[Lang{name: "HTML", category: FileType::Markup}][..]),
        (".html.hl", &[Lang{name: "HTML", category: FileType::Markup}][..]),
        (".st", &[Lang{name: "HTML", category: FileType::Markup},Lang{name: "Smalltalk", category: FileType::Programming}][..]),
        (".xht", &[Lang{name: "HTML", category: FileType::Markup}][..]),
        (".xhtml", &[Lang{name: "HTML", category: FileType::Markup}][..]),
        (".mustache", &[Lang{name: "HTML+Django", category: FileType::Markup}][..]),
        (".jinja", &[Lang{name: "HTML+Django", category: FileType::Markup}][..]),
        (".eex", &[Lang{name: "HTML+EEX", category: FileType::Markup}][..]),
        (".erb", &[Lang{name: "HTML+ERB", category: FileType::Markup}][..]),
        (".erb.deface", &[Lang{name: "HTML+ERB", category: FileType::Markup}][..]),
        (".phtml", &[Lang{name: "HTML+PHP", category: FileType::Markup}][..]),
        (".http", &[Lang{name: "HTTP", category: FileType::Data}][..]),
        (".php", &[Lang{name: "Hack", category: FileType::Programming},Lang{name: "PHP", category: FileType::Programming}][..]),
        (".haml", &[Lang{name: "Haml", category: FileType::Markup}][..]),
        (".haml.deface", &[Lang{name: "Haml", category: FileType::Markup}][..]),
        (".handlebars", &[Lang{name: "Handlebars", category: FileType::Markup}][..]),
        (".hbs", &[Lang{name: "Handlebars", category: FileType::Markup}][..]),
        (".hb", &[Lang{name: "Harbour", category: FileType::Programming}][..]),
        (".hs", &[Lang{name: "Haskell", category: FileType::Programming}][..]),
        (".hsc", &[Lang{name: "Haskell", category: FileType::Programming}][..]),
        (".hx", &[Lang{name: "Haxe", category: FileType::Programming}][..]),
        (".hxsl", &[Lang{name: "Haxe", category: FileType::Programming}][..]),
        (".hy", &[Lang{name: "Hy", category: FileType::Programming}][..]),
        (".pro", &[Lang{name: "IDL", category: FileType::Programming},Lang{name: "INI", category: FileType::Data},Lang{name: "Prolog", category: FileType::Programming},Lang{name: "QMake", category: FileType::Programming}][..]),
        (".dlm", &[Lang{name: "IDL", category: FileType::Programming}][..]),
        (".ipf", &[Lang{name: "IGOR Pro", category: FileType::Programming}][..]),
        (".ini", &[Lang{name: "INI", category: FileType::Data}][..]),
        (".cfg", &[Lang{name: "INI", category: FileType::Data}][..]),
        (".prefs", &[Lang{name: "INI", category: FileType::Data}][..]),
        (".properties", &[Lang{name: "INI", category: FileType::Data}][..]),
        (".irclog", &[Lang{name: "IRC log", category: FileType::Data}][..]),
        (".weechatlog", &[Lang{name: "IRC log", category: FileType::Data}][..]),
        (".idr", &[Lang{name: "Idris", category: FileType::Programming}][..]),
        (".lidr", &[Lang{name: "Idris", category: FileType::Programming}][..]),
        (".ni", &[Lang{name: "Inform 7", category: FileType::Programming}][..]),
        (".i7x", &[Lang{name: "Inform 7", category: FileType::Programming}][..]),
        (".iss", &[Lang{name: "Inno Setup", category: FileType::Programming}][..]),
        (".io", &[Lang{name: "Io", category: FileType::Programming}][..]),
        (".ik", &[Lang{name: "Ioke", category: FileType::Programming}][..]),
        (".thy", &[Lang{name: "Isabelle", category: FileType::Programming}][..]),
        (".ijs", &[Lang{name: "J", category: FileType::Programming}][..]),
        (".flex", &[Lang{name: "JFlex", category: FileType::Programming}][..]),
        (".jflex", &[Lang{name: "JFlex", category: FileType::Programming}][..]),
        (".json", &[Lang{name: "JSON", category: FileType::Data}][..]),
        (".geojson", &[Lang{name: "JSON", category: FileType::Data}][..]),
        (".lock", &[Lang{name: "JSON", category: FileType::Data}][..]),
        (".topojson", &[Lang{name: "JSON", category: FileType::Data}][..]),
        (".json5", &[Lang{name: "JSON5", category: FileType::Data}][..]),
        (".jsonld", &[Lang{name: "JSONLD", category: FileType::Data}][..]),
        (".jq", &[Lang{name: "JSONiq", category: FileType::Programming}][..]),
        (".jsx", &[Lang{name: "JSX", category: FileType::Programming}][..]),
        (".jade", &[Lang{name: "Jade", category: FileType::Markup}][..]),
        (".j", &[Lang{name: "Jasmin", category: FileType::Programming},Lang{name: "Objective-J", category: FileType::Programming}][..]),
        (".java", &[Lang{name: "Java", category: FileType::Programming}][..]),
        (".jsp", &[Lang{name: "Java Server Pages", category: FileType::Programming}][..]),
        (".js", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        ("._js", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".bones", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".es6", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".jake", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".jsb", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".jscad", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".jsfl", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".jsm", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".jss", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".njs", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".pac", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sjs", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".ssjs", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-build", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-commands", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-completions", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-keymap", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-macro", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-menu", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-mousemap", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-project", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-settings", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-theme", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime-workspace", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime_metrics", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".sublime_session", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".xsjs", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".xsjslib", &[Lang{name: "JavaScript", category: FileType::Programming}][..]),
        (".jl", &[Lang{name: "Julia", category: FileType::Programming}][..]),
        (".ipynb", &[Lang{name: "Jupyter Notebook", category: FileType::Markup}][..]),
        (".krl", &[Lang{name: "KRL", category: FileType::Programming}][..]),
        (".kicad_pcb", &[Lang{name: "KiCad", category: FileType::Programming}][..]),
        (".kit", &[Lang{name: "Kit", category: FileType::Markup}][..]),
        (".kt", &[Lang{name: "Kotlin", category: FileType::Programming}][..]),
        (".ktm", &[Lang{name: "Kotlin", category: FileType::Programming}][..]),
        (".kts", &[Lang{name: "Kotlin", category: FileType::Programming}][..]),
        (".lfe", &[Lang{name: "LFE", category: FileType::Programming}][..]),
        (".ll", &[Lang{name: "LLVM", category: FileType::Programming}][..]),
        (".lol", &[Lang{name: "LOLCODE", category: FileType::Programming}][..]),
        (".lsl", &[Lang{name: "LSL", category: FileType::Programming}][..]),
        (".lslp", &[Lang{name: "LSL", category: FileType::Programming}][..]),
        (".lvproj", &[Lang{name: "LabVIEW", category: FileType::Programming}][..]),
        (".lasso", &[Lang{name: "Lasso", category: FileType::Programming}][..]),
        (".las", &[Lang{name: "Lasso", category: FileType::Programming}][..]),
        (".lasso8", &[Lang{name: "Lasso", category: FileType::Programming}][..]),
        (".lasso9", &[Lang{name: "Lasso", category: FileType::Programming}][..]),
        (".ldml", &[Lang{name: "Lasso", category: FileType::Programming}][..]),
        (".latte", &[Lang{name: "Latte", category: FileType::Markup}][..]),
        (".lean", &[Lang{name: "Lean", category: FileType::Programming}][..]),
        (".hlean", &[Lang{name: "Lean", category: FileType::Programming}][..]),
        (".less", &[Lang{name: "Less", category: FileType::Markup}][..]),
        (".lex", &[Lang{name: "Lex", category: FileType::Programming}][..]),
        (".ly", &[Lang{name: "LilyPond", category: FileType::Programming}][..]),
        (".ily", &[Lang{name: "LilyPond", category: FileType::Programming}][..]),
        (".m", &[Lang{name: "Limbo", category: FileType::Programming},Lang{name: "M", category: FileType::Programming},Lang{name: "MUF", category: FileType::Programming},Lang{name: "Mathematica", category: FileType::Programming},Lang{name: "Matlab", category: FileType::Programming},Lang{name: "Mercury", category: FileType::Programming},Lang{name: "Objective-C", category: FileType::Programming}][..]),
        (".ld", &[Lang{name: "Linker Script", category: FileType::Data}][..]),
        (".lds", &[Lang{name: "Linker Script", category: FileType::Data}][..]),
        (".liquid", &[Lang{name: "Liquid", category: FileType::Markup}][..]),
        (".lagda", &[Lang{name: "Literate Agda", category: FileType::Programming}][..]),
        (".litcoffee", &[Lang{name: "Literate CoffeeScript", category: FileType::Programming}][..]),
        (".lhs", &[Lang{name: "Literate Haskell", category: FileType::Programming}][..]),
        (".ls", &[Lang{name: "LiveScript", category: FileType::Programming},Lang{name: "LoomScript", category: FileType::Programming}][..]),
        ("._ls", &[Lang{name: "LiveScript", category: FileType::Programming}][..]),
        (".xm", &[Lang{name: "Logos", category: FileType::Programming}][..]),
        (".x", &[Lang{name: "Logos", category: FileType::Programming}][..]),
        (".xi", &[Lang{name: "Logos", category: FileType::Programming}][..]),
        (".lgt", &[Lang{name: "Logtalk", category: FileType::Programming}][..]),
        (".logtalk", &[Lang{name: "Logtalk", category: FileType::Programming}][..]),
        (".lookml", &[Lang{name: "LookML", category: FileType::Programming}][..]),
        (".lua", &[Lang{name: "Lua", category: FileType::Programming}][..]),
        (".fcgi", &[Lang{name: "Lua", category: FileType::Programming},Lang{name: "PHP", category: FileType::Programming},Lang{name: "Perl", category: FileType::Programming},Lang{name: "Python", category: FileType::Programming},Lang{name: "Ruby", category: FileType::Programming},Lang{name: "Shell", category: FileType::Programming}][..]),
        (".nse", &[Lang{name: "Lua", category: FileType::Programming}][..]),
        (".pd_lua", &[Lang{name: "Lua", category: FileType::Programming}][..]),
        (".rbxs", &[Lang{name: "Lua", category: FileType::Programming}][..]),
        (".wlua", &[Lang{name: "Lua", category: FileType::Programming}][..]),
        (".mumps", &[Lang{name: "M", category: FileType::Programming}][..]),
        (".m4", &[Lang{name: "M4", category: FileType::Programming},Lang{name: "M4Sugar", category: FileType::Programming}][..]),
        (".mcr", &[Lang{name: "MAXScript", category: FileType::Programming}][..]),
        (".mtml", &[Lang{name: "MTML", category: FileType::Markup}][..]),
        (".muf", &[Lang{name: "MUF", category: FileType::Programming}][..]),
        (".mak", &[Lang{name: "Makefile", category: FileType::Programming}][..]),
        (".mk", &[Lang{name: "Makefile", category: FileType::Programming}][..]),
        (".mkfile", &[Lang{name: "Makefile", category: FileType::Programming}][..]),
        (".mako", &[Lang{name: "Mako", category: FileType::Programming}][..]),
        (".mao", &[Lang{name: "Mako", category: FileType::Programming}][..]),
        (".md", &[Lang{name: "Markdown", category: FileType::Prose}][..]),
        (".markdown", &[Lang{name: "Markdown", category: FileType::Prose}][..]),
        (".mkd", &[Lang{name: "Markdown", category: FileType::Prose}][..]),
        (".mkdn", &[Lang{name: "Markdown", category: FileType::Prose}][..]),
        (".mkdown", &[Lang{name: "Markdown", category: FileType::Prose}][..]),
        (".ron", &[Lang{name: "Markdown", category: FileType::Prose}][..]),
        (".mask", &[Lang{name: "Mask", category: FileType::Markup}][..]),
        (".mathematica", &[Lang{name: "Mathematica", category: FileType::Programming}][..]),
        (".cdf", &[Lang{name: "Mathematica", category: FileType::Programming}][..]),
        (".ma", &[Lang{name: "Mathematica", category: FileType::Programming}][..]),
        (".mt", &[Lang{name: "Mathematica", category: FileType::Programming}][..]),
        (".nb", &[Lang{name: "Mathematica", category: FileType::Programming},Lang{name: "Text", category: FileType::Prose}][..]),
        (".nbp", &[Lang{name: "Mathematica", category: FileType::Programming}][..]),
        (".wl", &[Lang{name: "Mathematica", category: FileType::Programming}][..]),
        (".wlt", &[Lang{name: "Mathematica", category: FileType::Programming}][..]),
        (".matlab", &[Lang{name: "Matlab", category: FileType::Programming}][..]),
        (".maxpat", &[Lang{name: "Max", category: FileType::Programming}][..]),
        (".maxhelp", &[Lang{name: "Max", category: FileType::Programming}][..]),
        (".maxproj", &[Lang{name: "Max", category: FileType::Programming}][..]),
        (".mxt", &[Lang{name: "Max", category: FileType::Programming}][..]),
        (".pat", &[Lang{name: "Max", category: FileType::Programming}][..]),
        (".mediawiki", &[Lang{name: "MediaWiki", category: FileType::Prose}][..]),
        (".wiki", &[Lang{name: "MediaWiki", category: FileType::Prose}][..]),
        (".moo", &[Lang{name: "Mercury", category: FileType::Programming},Lang{name: "Moocode", category: FileType::Programming}][..]),
        (".metal", &[Lang{name: "Metal", category: FileType::Programming}][..]),
        (".minid", &[Lang{name: "MiniD", category: FileType::Programming}][..]),
        (".druby", &[Lang{name: "Mirah", category: FileType::Programming}][..]),
        (".duby", &[Lang{name: "Mirah", category: FileType::Programming}][..]),
        (".mir", &[Lang{name: "Mirah", category: FileType::Programming}][..]),
        (".mirah", &[Lang{name: "Mirah", category: FileType::Programming}][..]),
        (".mo", &[Lang{name: "Modelica", category: FileType::Programming}][..]),
        (".mms", &[Lang{name: "Module Management System", category: FileType::Programming}][..]),
        (".mmk", &[Lang{name: "Module Management System", category: FileType::Programming}][..]),
        (".monkey", &[Lang{name: "Monkey", category: FileType::Programming}][..]),
        (".moon", &[Lang{name: "MoonScript", category: FileType::Programming}][..]),
        (".myt", &[Lang{name: "Myghty", category: FileType::Programming}][..]),
        (".ncl", &[Lang{name: "NCL", category: FileType::Programming},Lang{name: "Text", category: FileType::Prose}][..]),
        (".nl", &[Lang{name: "NL", category: FileType::Data},Lang{name: "NewLisp", category: FileType::Programming}][..]),
        (".nsi", &[Lang{name: "NSIS", category: FileType::Programming}][..]),
        (".nsh", &[Lang{name: "NSIS", category: FileType::Programming}][..]),
        (".axs", &[Lang{name: "NetLinx", category: FileType::Programming}][..]),
        (".axi", &[Lang{name: "NetLinx", category: FileType::Programming}][..]),
        (".axs.erb", &[Lang{name: "NetLinx+ERB", category: FileType::Programming}][..]),
        (".axi.erb", &[Lang{name: "NetLinx+ERB", category: FileType::Programming}][..]),
        (".nlogo", &[Lang{name: "NetLogo", category: FileType::Programming}][..]),
        (".nginxconf", &[Lang{name: "Nginx", category: FileType::Markup}][..]),
        (".nim", &[Lang{name: "Nimrod", category: FileType::Programming}][..]),
        (".nimrod", &[Lang{name: "Nimrod", category: FileType::Programming}][..]),
        (".ninja", &[Lang{name: "Ninja", category: FileType::Data}][..]),
        (".nit", &[Lang{name: "Nit", category: FileType::Programming}][..]),
        (".nix", &[Lang{name: "Nix", category: FileType::Programming}][..]),
        (".nu", &[Lang{name: "Nu", category: FileType::Programming}][..]),
        (".numpy", &[Lang{name: "NumPy", category: FileType::Programming}][..]),
        (".numpyw", &[Lang{name: "NumPy", category: FileType::Programming}][..]),
        (".numsc", &[Lang{name: "NumPy", category: FileType::Programming}][..]),
        (".ml", &[Lang{name: "OCaml", category: FileType::Programming}][..]),
        (".eliom", &[Lang{name: "OCaml", category: FileType::Programming}][..]),
        (".eliomi", &[Lang{name: "OCaml", category: FileType::Programming}][..]),
        (".ml4", &[Lang{name: "OCaml", category: FileType::Programming}][..]),
        (".mli", &[Lang{name: "OCaml", category: FileType::Programming}][..]),
        (".mll", &[Lang{name: "OCaml", category: FileType::Programming}][..]),
        (".mly", &[Lang{name: "OCaml", category: FileType::Programming}][..]),
        (".objdump", &[Lang{name: "ObjDump", category: FileType::Data}][..]),
        (".mm", &[Lang{name: "Objective-C++", category: FileType::Programming},Lang{name: "XML", category: FileType::Data}][..]),
        (".sj", &[Lang{name: "Objective-J", category: FileType::Programming}][..]),
        (".omgrofl", &[Lang{name: "Omgrofl", category: FileType::Programming}][..]),
        (".opa", &[Lang{name: "Opa", category: FileType::Programming}][..]),
        (".opal", &[Lang{name: "Opal", category: FileType::Programming}][..]),
        (".opencl", &[Lang{name: "OpenCL", category: FileType::Programming}][..]),
        (".p", &[Lang{name: "OpenEdge ABL", category: FileType::Programming}][..]),
        (".scad", &[Lang{name: "OpenSCAD", category: FileType::Programming}][..]),
        (".org", &[Lang{name: "Org", category: FileType::Prose}][..]),
        (".ox", &[Lang{name: "Ox", category: FileType::Programming}][..]),
        (".oxh", &[Lang{name: "Ox", category: FileType::Programming}][..]),
        (".oxo", &[Lang{name: "Ox", category: FileType::Programming}][..]),
        (".oxygene", &[Lang{name: "Oxygene", category: FileType::Programming}][..]),
        (".oz", &[Lang{name: "Oz", category: FileType::Programming}][..]),
        (".pwn", &[Lang{name: "PAWN", category: FileType::Programming}][..]),
        (".aw", &[Lang{name: "PHP", category: FileType::Programming}][..]),
        (".ctp", &[Lang{name: "PHP", category: FileType::Programming}][..]),
        (".php3", &[Lang{name: "PHP", category: FileType::Programming}][..]),
        (".php4", &[Lang{name: "PHP", category: FileType::Programming}][..]),
        (".php5", &[Lang{name: "PHP", category: FileType::Programming}][..]),
        (".phps", &[Lang{name: "PHP", category: FileType::Programming}][..]),
        (".phpt", &[Lang{name: "PHP", category: FileType::Programming}][..]),
        (".pls", &[Lang{name: "PLSQL", category: FileType::Programming}][..]),
        (".pck", &[Lang{name: "PLSQL", category: FileType::Programming}][..]),
        (".pkb", &[Lang{name: "PLSQL", category: FileType::Programming}][..]),
        (".pks", &[Lang{name: "PLSQL", category: FileType::Programming}][..]),
        (".plb", &[Lang{name: "PLSQL", category: FileType::Programming}][..]),
        (".plsql", &[Lang{name: "PLSQL", category: FileType::Programming}][..]),
        (".sql", &[Lang{name: "PLSQL", category: FileType::Programming},Lang{name: "PLpgSQL", category: FileType::Programming},Lang{name: "SQL", category: FileType::Data},Lang{name: "SQLPL", category: FileType::Programming}][..]),
        (".pov", &[Lang{name: "POV-Ray SDL", category: FileType::Programming}][..]),
        (".pan", &[Lang{name: "Pan", category: FileType::Programming}][..]),
        (".psc", &[Lang{name: "Papyrus", category: FileType::Programming}][..]),
        (".parrot", &[Lang{name: "Parrot", category: FileType::Programming}][..]),
        (".pasm", &[Lang{name: "Parrot Assembly", category: FileType::Programming}][..]),
        (".pir", &[Lang{name: "Parrot Internal Representation", category: FileType::Programming}][..]),
        (".pas", &[Lang{name: "Pascal", category: FileType::Programming}][..]),
        (".dfm", &[Lang{name: "Pascal", category: FileType::Programming}][..]),
        (".dpr", &[Lang{name: "Pascal", category: FileType::Programming}][..]),
        (".lpr", &[Lang{name: "Pascal", category: FileType::Programming}][..]),
        (".pp", &[Lang{name: "Pascal", category: FileType::Programming},Lang{name: "Puppet", category: FileType::Programming}][..]),
        (".pl", &[Lang{name: "Perl", category: FileType::Programming},Lang{name: "Perl6", category: FileType::Programming},Lang{name: "Prolog", category: FileType::Programming}][..]),
        (".al", &[Lang{name: "Perl", category: FileType::Programming}][..]),
        (".cgi", &[Lang{name: "Perl", category: FileType::Programming},Lang{name: "Python", category: FileType::Programming},Lang{name: "Shell", category: FileType::Programming}][..]),
        (".perl", &[Lang{name: "Perl", category: FileType::Programming}][..]),
        (".ph", &[Lang{name: "Perl", category: FileType::Programming}][..]),
        (".plx", &[Lang{name: "Perl", category: FileType::Programming}][..]),
        (".pm", &[Lang{name: "Perl", category: FileType::Programming},Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".pod", &[Lang{name: "Perl", category: FileType::Programming},Lang{name: "Pod", category: FileType::Prose}][..]),
        (".psgi", &[Lang{name: "Perl", category: FileType::Programming}][..]),
        (".t", &[Lang{name: "Perl", category: FileType::Programming},Lang{name: "Perl6", category: FileType::Programming},Lang{name: "Terra", category: FileType::Programming},Lang{name: "Turing", category: FileType::Programming}][..]),
        (".6pl", &[Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".6pm", &[Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".nqp", &[Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".p6", &[Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".p6l", &[Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".p6m", &[Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".pl6", &[Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".pm6", &[Lang{name: "Perl6", category: FileType::Programming}][..]),
        (".pkl", &[Lang{name: "Pickle", category: FileType::Data}][..]),
        (".pig", &[Lang{name: "PigLatin", category: FileType::Programming}][..]),
        (".pike", &[Lang{name: "Pike", category: FileType::Programming}][..]),
        (".pmod", &[Lang{name: "Pike", category: FileType::Programming}][..]),
        (".pogo", &[Lang{name: "PogoScript", category: FileType::Programming}][..]),
        (".pony", &[Lang{name: "Pony", category: FileType::Programming}][..]),
        (".ps", &[Lang{name: "PostScript", category: FileType::Markup}][..]),
        (".eps", &[Lang{name: "PostScript", category: FileType::Markup}][..]),
        (".ps1", &[Lang{name: "PowerShell", category: FileType::Programming}][..]),
        (".psd1", &[Lang{name: "PowerShell", category: FileType::Programming}][..]),
        (".psm1", &[Lang{name: "PowerShell", category: FileType::Programming}][..]),
        (".pde", &[Lang{name: "Processing", category: FileType::Programming}][..]),
        (".prolog", &[Lang{name: "Prolog", category: FileType::Programming}][..]),
        (".yap", &[Lang{name: "Prolog", category: FileType::Programming}][..]),
        (".spin", &[Lang{name: "Propeller Spin", category: FileType::Programming}][..]),
        (".proto", &[Lang{name: "Protocol Buffer", category: FileType::Markup}][..]),
        (".pub", &[Lang{name: "Public Key", category: FileType::Data}][..]),
        (".pd", &[Lang{name: "Pure Data", category: FileType::Programming}][..]),
        (".pb", &[Lang{name: "PureBasic", category: FileType::Programming}][..]),
        (".pbi", &[Lang{name: "PureBasic", category: FileType::Programming}][..]),
        (".purs", &[Lang{name: "PureScript", category: FileType::Programming}][..]),
        (".py", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".bzl", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".gyp", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".lmi", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".pyde", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".pyp", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".pyt", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".pyw", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".rpy", &[Lang{name: "Python", category: FileType::Programming},Lang{name: "Ren'Py", category: FileType::Programming}][..]),
        (".tac", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".wsgi", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".xpy", &[Lang{name: "Python", category: FileType::Programming}][..]),
        (".pytb", &[Lang{name: "Python traceback", category: FileType::Data}][..]),
        (".qml", &[Lang{name: "QML", category: FileType::Programming}][..]),
        (".qbs", &[Lang{name: "QML", category: FileType::Programming}][..]),
        (".pri", &[Lang{name: "QMake", category: FileType::Programming}][..]),
        (".r", &[Lang{name: "R", category: FileType::Programming},Lang{name: "Rebol", category: FileType::Programming}][..]),
        (".rd", &[Lang{name: "R", category: FileType::Programming}][..]),
        (".rsx", &[Lang{name: "R", category: FileType::Programming}][..]),
        (".raml", &[Lang{name: "RAML", category: FileType::Markup}][..]),
        (".rdoc", &[Lang{name: "RDoc", category: FileType::Prose}][..]),
        (".rbbas", &[Lang{name: "REALbasic", category: FileType::Programming}][..]),
        (".rbfrm", &[Lang{name: "REALbasic", category: FileType::Programming}][..]),
        (".rbmnu", &[Lang{name: "REALbasic", category: FileType::Programming}][..]),
        (".rbres", &[Lang{name: "REALbasic", category: FileType::Programming}][..]),
        (".rbtbar", &[Lang{name: "REALbasic", category: FileType::Programming}][..]),
        (".rbuistate", &[Lang{name: "REALbasic", category: FileType::Programming}][..]),
        (".rhtml", &[Lang{name: "RHTML", category: FileType::Markup}][..]),
        (".rmd", &[Lang{name: "RMarkdown", category: FileType::Prose}][..]),
        (".rkt", &[Lang{name: "Racket", category: FileType::Programming}][..]),
        (".rktd", &[Lang{name: "Racket", category: FileType::Programming}][..]),
        (".rktl", &[Lang{name: "Racket", category: FileType::Programming}][..]),
        (".scrbl", &[Lang{name: "Racket", category: FileType::Programming}][..]),
        (".rl", &[Lang{name: "Ragel in Ruby Host", category: FileType::Programming}][..]),
        (".raw", &[Lang{name: "Raw token data", category: FileType::Data}][..]),
        (".reb", &[Lang{name: "Rebol", category: FileType::Programming}][..]),
        (".r2", &[Lang{name: "Rebol", category: FileType::Programming}][..]),
        (".r3", &[Lang{name: "Rebol", category: FileType::Programming}][..]),
        (".rebol", &[Lang{name: "Rebol", category: FileType::Programming}][..]),
        (".red", &[Lang{name: "Red", category: FileType::Programming}][..]),
        (".reds", &[Lang{name: "Red", category: FileType::Programming}][..]),
        (".cw", &[Lang{name: "Redcode", category: FileType::Programming}][..]),
        (".rs", &[Lang{name: "RenderScript", category: FileType::Programming},Lang{name: "Rust", category: FileType::Programming}][..]),
        (".rsh", &[Lang{name: "RenderScript", category: FileType::Programming}][..]),
        (".robot", &[Lang{name: "RobotFramework", category: FileType::Programming}][..]),
        (".rg", &[Lang{name: "Rouge", category: FileType::Programming}][..]),
        (".rb", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".builder", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".gemspec", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".god", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".irbrc", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".jbuilder", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".mspec", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".pluginspec", &[Lang{name: "Ruby", category: FileType::Programming},Lang{name: "XML", category: FileType::Data}][..]),
        (".podspec", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".rabl", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".rake", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".rbuild", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".rbw", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".rbx", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".ru", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".ruby", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".thor", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".watchr", &[Lang{name: "Ruby", category: FileType::Programming}][..]),
        (".rs.in", &[Lang{name: "Rust", category: FileType::Programming}][..]),
        (".sas", &[Lang{name: "SAS", category: FileType::Programming}][..]),
        (".scss", &[Lang{name: "SCSS", category: FileType::Markup}][..]),
        (".smt2", &[Lang{name: "SMT", category: FileType::Programming}][..]),
        (".smt", &[Lang{name: "SMT", category: FileType::Programming}][..]),
        (".sparql", &[Lang{name: "SPARQL", category: FileType::Data}][..]),
        (".rq", &[Lang{name: "SPARQL", category: FileType::Data}][..]),
        (".sqf", &[Lang{name: "SQF", category: FileType::Programming}][..]),
        (".hqf", &[Lang{name: "SQF", category: FileType::Programming}][..]),
        (".cql", &[Lang{name: "SQL", category: FileType::Data}][..]),
        (".ddl", &[Lang{name: "SQL", category: FileType::Data}][..]),
        (".prc", &[Lang{name: "SQL", category: FileType::Data}][..]),
        (".tab", &[Lang{name: "SQL", category: FileType::Data}][..]),
        (".udf", &[Lang{name: "SQL", category: FileType::Data}][..]),
        (".viw", &[Lang{name: "SQL", category: FileType::Data}][..]),
        (".db2", &[Lang{name: "SQLPL", category: FileType::Programming}][..]),
        (".ston", &[Lang{name: "STON", category: FileType::Data}][..]),
        (".svg", &[Lang{name: "SVG", category: FileType::Data}][..]),
        (".sage", &[Lang{name: "Sage", category: FileType::Programming}][..]),
        (".sagews", &[Lang{name: "Sage", category: FileType::Programming}][..]),
        (".sls", &[Lang{name: "SaltStack", category: FileType::Programming},Lang{name: "Scheme", category: FileType::Programming}][..]),
        (".sass", &[Lang{name: "Sass", category: FileType::Markup}][..]),
        (".scala", &[Lang{name: "Scala", category: FileType::Programming}][..]),
        (".sbt", &[Lang{name: "Scala", category: FileType::Programming}][..]),
        (".sc", &[Lang{name: "Scala", category: FileType::Programming},Lang{name: "SuperCollider", category: FileType::Programming}][..]),
        (".scaml", &[Lang{name: "Scaml", category: FileType::Markup}][..]),
        (".scm", &[Lang{name: "Scheme", category: FileType::Programming}][..]),
        (".sld", &[Lang{name: "Scheme", category: FileType::Programming}][..]),
        (".sps", &[Lang{name: "Scheme", category: FileType::Programming}][..]),
        (".ss", &[Lang{name: "Scheme", category: FileType::Programming}][..]),
        (".sci", &[Lang{name: "Scilab", category: FileType::Programming}][..]),
        (".sce", &[Lang{name: "Scilab", category: FileType::Programming}][..]),
        (".self", &[Lang{name: "Self", category: FileType::Programming}][..]),
        (".sh", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".bash", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".bats", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".command", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".ksh", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".sh.in", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".tmux", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".tool", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".zsh", &[Lang{name: "Shell", category: FileType::Programming}][..]),
        (".sh-session", &[Lang{name: "ShellSession", category: FileType::Programming}][..]),
        (".shen", &[Lang{name: "Shen", category: FileType::Programming}][..]),
        (".sl", &[Lang{name: "Slash", category: FileType::Programming}][..]),
        (".slim", &[Lang{name: "Slim", category: FileType::Markup}][..]),
        (".smali", &[Lang{name: "Smali", category: FileType::Programming}][..]),
        (".tpl", &[Lang{name: "Smarty", category: FileType::Programming}][..]),
        (".sp", &[Lang{name: "SourcePawn", category: FileType::Programming}][..]),
        (".sma", &[Lang{name: "SourcePawn", category: FileType::Programming}][..]),
        (".nut", &[Lang{name: "Squirrel", category: FileType::Programming}][..]),
        (".stan", &[Lang{name: "Stan", category: FileType::Programming}][..]),
        (".ML", &[Lang{name: "Standard ML", category: FileType::Programming}][..]),
        (".fun", &[Lang{name: "Standard ML", category: FileType::Programming}][..]),
        (".sig", &[Lang{name: "Standard ML", category: FileType::Programming}][..]),
        (".sml", &[Lang{name: "Standard ML", category: FileType::Programming}][..]),
        (".do", &[Lang{name: "Stata", category: FileType::Programming}][..]),
        (".ado", &[Lang{name: "Stata", category: FileType::Programming}][..]),
        (".doh", &[Lang{name: "Stata", category: FileType::Programming}][..]),
        (".ihlp", &[Lang{name: "Stata", category: FileType::Programming}][..]),
        (".mata", &[Lang{name: "Stata", category: FileType::Programming}][..]),
        (".matah", &[Lang{name: "Stata", category: FileType::Programming}][..]),
        (".sthlp", &[Lang{name: "Stata", category: FileType::Programming}][..]),
        (".styl", &[Lang{name: "Stylus", category: FileType::Markup}][..]),
        (".scd", &[Lang{name: "SuperCollider", category: FileType::Programming}][..]),
        (".swift", &[Lang{name: "Swift", category: FileType::Programming}][..]),
        (".sv", &[Lang{name: "SystemVerilog", category: FileType::Programming}][..]),
        (".svh", &[Lang{name: "SystemVerilog", category: FileType::Programming}][..]),
        (".vh", &[Lang{name: "SystemVerilog", category: FileType::Programming}][..]),
        (".toml", &[Lang{name: "TOML", category: FileType::Data}][..]),
        (".txl", &[Lang{name: "TXL", category: FileType::Programming}][..]),
        (".tcl", &[Lang{name: "Tcl", category: FileType::Programming}][..]),
        (".adp", &[Lang{name: "Tcl", category: FileType::Programming}][..]),
        (".tm", &[Lang{name: "Tcl", category: FileType::Programming}][..]),
        (".tcsh", &[Lang{name: "Tcsh", category: FileType::Programming}][..]),
        (".csh", &[Lang{name: "Tcsh", category: FileType::Programming}][..]),
        (".tex", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".aux", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".bbx", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".bib", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".cbx", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".dtx", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".ins", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".lbx", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".ltx", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".mkii", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".mkiv", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".mkvi", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".sty", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".toc", &[Lang{name: "TeX", category: FileType::Markup}][..]),
        (".tea", &[Lang{name: "Tea", category: FileType::Markup}][..]),
        (".txt", &[Lang{name: "Text", category: FileType::Prose}][..]),
        (".no", &[Lang{name: "Text", category: FileType::Prose}][..]),
        (".textile", &[Lang{name: "Textile", category: FileType::Prose}][..]),
        (".thrift", &[Lang{name: "Thrift", category: FileType::Programming}][..]),
        (".tu", &[Lang{name: "Turing", category: FileType::Programming}][..]),
        (".ttl", &[Lang{name: "Turtle", category: FileType::Data}][..]),
        (".twig", &[Lang{name: "Twig", category: FileType::Markup}][..]),
        (".ts", &[Lang{name: "TypeScript", category: FileType::Programming},Lang{name: "XML", category: FileType::Data}][..]),
        (".tsx", &[Lang{name: "TypeScript", category: FileType::Programming},Lang{name: "XML", category: FileType::Data}][..]),
        (".upc", &[Lang{name: "Unified Parallel C", category: FileType::Programming}][..]),
        (".anim", &[Lang{name: "Unity3D Asset", category: FileType::Data}][..]),
        (".asset", &[Lang{name: "Unity3D Asset", category: FileType::Data}][..]),
        (".mat", &[Lang{name: "Unity3D Asset", category: FileType::Data}][..]),
        (".meta", &[Lang{name: "Unity3D Asset", category: FileType::Data}][..]),
        (".prefab", &[Lang{name: "Unity3D Asset", category: FileType::Data}][..]),
        (".unity", &[Lang{name: "Unity3D Asset", category: FileType::Data}][..]),
        (".uno", &[Lang{name: "Uno", category: FileType::Programming}][..]),
        (".uc", &[Lang{name: "UnrealScript", category: FileType::Programming}][..]),
        (".ur", &[Lang{name: "UrWeb", category: FileType::Programming}][..]),
        (".urs", &[Lang{name: "UrWeb", category: FileType::Programming}][..]),
        (".vcl", &[Lang{name: "VCL", category: FileType::Programming}][..]),
        (".vhdl", &[Lang{name: "VHDL", category: FileType::Programming}][..]),
        (".vhd", &[Lang{name: "VHDL", category: FileType::Programming}][..]),
        (".vhf", &[Lang{name: "VHDL", category: FileType::Programming}][..]),
        (".vhi", &[Lang{name: "VHDL", category: FileType::Programming}][..]),
        (".vho", &[Lang{name: "VHDL", category: FileType::Programming}][..]),
        (".vhs", &[Lang{name: "VHDL", category: FileType::Programming}][..]),
        (".vht", &[Lang{name: "VHDL", category: FileType::Programming}][..]),
        (".vhw", &[Lang{name: "VHDL", category: FileType::Programming}][..]),
        (".vala", &[Lang{name: "Vala", category: FileType::Programming}][..]),
        (".vapi", &[Lang{name: "Vala", category: FileType::Programming}][..]),
        (".veo", &[Lang{name: "Verilog", category: FileType::Programming}][..]),
        (".vim", &[Lang{name: "VimL", category: FileType::Programming}][..]),
        (".vb", &[Lang{name: "Visual Basic", category: FileType::Programming}][..]),
        (".bas", &[Lang{name: "Visual Basic", category: FileType::Programming}][..]),
        (".frm", &[Lang{name: "Visual Basic", category: FileType::Programming}][..]),
        (".frx", &[Lang{name: "Visual Basic", category: FileType::Programming}][..]),
        (".vba", &[Lang{name: "Visual Basic", category: FileType::Programming}][..]),
        (".vbhtml", &[Lang{name: "Visual Basic", category: FileType::Programming}][..]),
        (".vbs", &[Lang{name: "Visual Basic", category: FileType::Programming}][..]),
        (".volt", &[Lang{name: "Volt", category: FileType::Programming}][..]),
        (".vue", &[Lang{name: "Vue", category: FileType::Markup}][..]),
        (".owl", &[Lang{name: "Web Ontology Language", category: FileType::Markup}][..]),
        (".webidl", &[Lang{name: "WebIDL", category: FileType::Programming}][..]),
        (".x10", &[Lang{name: "X10", category: FileType::Programming}][..]),
        (".xc", &[Lang{name: "XC", category: FileType::Programming}][..]),
        (".xml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ant", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".axml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ccxml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".clixml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".cproject", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".csl", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".csproj", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ct", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".dita", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ditamap", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ditaval", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".dll.config", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".dotsettings", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".filters", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".fsproj", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".fxml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".glade", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".grxml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".iml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ivy", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".jelly", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".jsproj", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".kml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".launch", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".mdpolicy", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".mxml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".nproj", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".nuspec", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".odd", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".osm", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".plist", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".props", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ps1xml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".psc1", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".pt", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".rdf", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".rss", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".scxml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".srdf", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".storyboard", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".stTheme", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".sublime-snippet", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".targets", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".tmCommand", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".tml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".tmLanguage", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".tmPreferences", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".tmSnippet", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".tmTheme", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ui", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".urdf", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".ux", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".vbproj", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".vcxproj", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".vssettings", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".vxml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".wsdl", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".wsf", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".wxi", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".wxl", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".wxs", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".x3d", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xacro", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xaml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xib", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xlf", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xliff", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xmi", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xml.dist", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xproj", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xsd", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xul", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".zcml", &[Lang{name: "XML", category: FileType::Data}][..]),
        (".xsp-config", &[Lang{name: "XPages", category: FileType::Programming}][..]),
        (".xsp.metadata", &[Lang{name: "XPages", category: FileType::Programming}][..]),
        (".xpl", &[Lang{name: "XProc", category: FileType::Programming}][..]),
        (".xproc", &[Lang{name: "XProc", category: FileType::Programming}][..]),
        (".xquery", &[Lang{name: "XQuery", category: FileType::Programming}][..]),
        (".xq", &[Lang{name: "XQuery", category: FileType::Programming}][..]),
        (".xql", &[Lang{name: "XQuery", category: FileType::Programming}][..]),
        (".xqm", &[Lang{name: "XQuery", category: FileType::Programming}][..]),
        (".xqy", &[Lang{name: "XQuery", category: FileType::Programming}][..]),
        (".xs", &[Lang{name: "XS", category: FileType::Programming}][..]),
        (".xslt", &[Lang{name: "XSLT", category: FileType::Programming}][..]),
        (".xsl", &[Lang{name: "XSLT", category: FileType::Programming}][..]),
        (".xojo_code", &[Lang{name: "Xojo", category: FileType::Programming}][..]),
        (".xojo_menu", &[Lang{name: "Xojo", category: FileType::Programming}][..]),
        (".xojo_report", &[Lang{name: "Xojo", category: FileType::Programming}][..]),
        (".xojo_script", &[Lang{name: "Xojo", category: FileType::Programming}][..]),
        (".xojo_toolbar", &[Lang{name: "Xojo", category: FileType::Programming}][..]),
        (".xojo_window", &[Lang{name: "Xojo", category: FileType::Programming}][..]),
        (".xtend", &[Lang{name: "Xtend", category: FileType::Programming}][..]),
        (".yml", &[Lang{name: "YAML", category: FileType::Data}][..]),
        (".reek", &[Lang{name: "YAML", category: FileType::Data}][..]),
        (".rviz", &[Lang{name: "YAML", category: FileType::Data}][..]),
        (".sublime-syntax", &[Lang{name: "YAML", category: FileType::Data}][..]),
        (".syntax", &[Lang{name: "YAML", category: FileType::Data}][..]),
        (".yaml", &[Lang{name: "YAML", category: FileType::Data}][..]),
        (".yaml-tmlanguage", &[Lang{name: "YAML", category: FileType::Data}][..]),
        (".yang", &[Lang{name: "YANG", category: FileType::Data}][..]),
        (".y", &[Lang{name: "Yacc", category: FileType::Programming}][..]),
        (".yacc", &[Lang{name: "Yacc", category: FileType::Programming}][..]),
        (".yy", &[Lang{name: "Yacc", category: FileType::Programming}][..]),
        (".zep", &[Lang{name: "Zephir", category: FileType::Programming}][..]),
        (".zimpl", &[Lang{name: "Zimpl", category: FileType::Programming}][..]),
        (".zmpl", &[Lang{name: "Zimpl", category: FileType::Programming}][..]),
        (".zpl", &[Lang{name: "Zimpl", category: FileType::Programming}][..]),
        (".desktop", &[Lang{name: "desktop", category: FileType::Data}][..]),
        (".desktop.in", &[Lang{name: "desktop", category: FileType::Data}][..]),
        (".ec", &[Lang{name: "eC", category: FileType::Programming}][..]),
        (".eh", &[Lang{name: "eC", category: FileType::Programming}][..]),
        (".edn", &[Lang{name: "edn", category: FileType::Data}][..]),
        (".fish", &[Lang{name: "fish", category: FileType::Programming}][..]),
        (".mu", &[Lang{name: "mupad", category: FileType::Programming}][..]),
        (".nc", &[Lang{name: "nesC", category: FileType::Programming}][..]),
        (".ooc", &[Lang{name: "ooc", category: FileType::Programming}][..]),
        (".rst", &[Lang{name: "reStructuredText", category: FileType::Prose}][..]),
        (".rest", &[Lang{name: "reStructuredText", category: FileType::Prose}][..]),
        (".rest.txt", &[Lang{name: "reStructuredText", category: FileType::Prose}][..]),
        (".rst.txt", &[Lang{name: "reStructuredText", category: FileType::Prose}][..]),
        (".wisp", &[Lang{name: "wisp", category: FileType::Programming}][..]),
        (".prg", &[Lang{name: "xBase", category: FileType::Programming}][..]),
        (".prw", &[Lang{name: "xBase", category: FileType::Programming}][..])
    ]);
}
